### ISSUE TITLE
Wallet address not shown after connect wallet for the first time

### ISSUE THREAD

**Issue by Chomtana** [code-423n4/code423n4.com#2194] opened 2022-06-14 17:07 UTC
## Screenshot
![code4renaconnect](https://user-images.githubusercontent.com/4103490/173635950-82ed6631-1133-45e1-b4e1-7152ab805c41.png)

## Video
https://user-images.githubusercontent.com/4103490/173636018-81ea6c33-2f1b-4eeb-b310-358f26e67eb7.mp4

## Issue
Wallet address not shown after connect wallet for the first time. Moreover, dropdown still prompt user to connect their wallet even though it has been connected.

## Recommendation
- After connect wallet, wallet address must be shown
- Dropdown menu should be changed from connect wallet to logout / profile button

**Comment by captainmangoC4** [comment] 2022-06-14 17:49
Thanks for the suggestion! This was actually by design, but I think we can make the UX more clear. The user cannot officially be "logged in" until they enter the details in the form above and click "submit." Basically, we just need the user to confirm their identity before we officially re-register them and allow them to "log in" and submit findings.

To make that clear to the user, we chose to not show the user dropdown with logout option until they are confirmed and the PR updating their warden file is merged. Maybe an alternative could be to show the user dropdown, but say "pending" next to their handle? Or maybe display their address somewhere in the form?

What do you think @tealtigrrr

**Comment by captainmangoC4** [comment] 2022-06-14 18:01
At the very least, we should not show the "connect wallet" dropdown in this case, as @Chomtana suggested.

**Comment by Chomtana** [comment] 2022-06-14 18:19
And show connected wallet address in the form as a disabled input

**Comment by eugenioclrc** [comment] 2022-06-14 19:09
Same thoughts here...

Lets say this is the first time im on code4rena, i want to register, so i click con the connect button, i sign the message so i think im already login, but since i got no user associated i end up on the /register page.

But in there i see the "connect wallet" again and have the same issue...

One simple solution could be hide the connect wallet button in the "/register" page to avoid confusion.

**Comment by captainmangoC4** [comment] 2022-06-14 21:28
> One simple solution could be hide the connect wallet button in the "/register" page to avoid confusion.

Great point, I definitely like that idea. Maybe the `DefaultLayout` component can take an optional prop for whether or not to show the connect wallet dropdown.

> Other thing that could be done its to just ask for user wallet address permission, if we saw that this wallet its not a registered user then there is no need to do the sign message, he must first fill the registration and he will sign the message in that page.

I didn't consider this as an option, but I love this idea. Do you know if there is some way to do this with built-in moralis functionality, or are you thinking of writing a cloud function that would do this? It would have to check the `AddressesFromPreviousSubmissions` table as well as the `_User` table.

**Comment by captainmangoC4** [comment] 2022-06-14 21:33
> Or you may change "Connect Wallet" button to "Register"?

The original design for the feature actually did have a separate login button and register button, but the decision to change the design and have one "connect wallet" button was made so that it would feel a little more streamlined and secure, particularly for existing wardens who aren't exactly registering, just confirming their identity and linking it to their wallet.

**Comment by captainmangoC4** [comment] 2022-06-14 21:35
> And show connected wallet address in the form as a disabled input

I think this is also a good option, especially in combination with hiding the connect wallet button on register and confirm account pages.

**Comment by eugenioclrc** [comment] 2022-06-15 04:12
> I didn't consider this as an option, but I love this idea. Do you know if there is some way to do this with built-in moralis functionality, or are you thinking of writing a cloud function that would do this? It would have to check the `AddressesFromPreviousSubmissions` table as well as the `_User` table.

I dont think so, but i think the happy path would be, user connect wallet and sign with Moralis, then if wallet its not registered the connect wallet should switch for a "register" button, also user should be redirected to the register page.

**Comment by eugenioclrc** [comment] 2022-06-15 10:08
+1

**Closed** 2022-06-22 04:39 UTC
Labels: [EPIC] warden reg, External request, Accepted issue
